sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only

# before_install:
# - npm install -g hexo

# install:
# - npm install

# # Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
# before_script:
# - git config --global user.name 'yummygyudon'
# - git config --global user.email 'bang2brew@gmail.com'
# # - git clone git://github.com/heroicyang/hexo-theme-modernist.git themes/modernist

script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
  
# after_success:
# - mkdir .deploy                   # Create a folder to use for teh pages branch
# - cd .deploy
# - git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
# - rm -rf ./*                      # Clear old verion
# - cp -r ../public/* .             # Copy over files for new version
# - git add -A .          
# - git commit -m 'Site updated'    # Make a new commit for new version
# - git branch -m gh-pages
# - git push -q -u origin gh-pages  # Push silently so we don't leak information
